name: Karma-tests

on:
  pull_request:
    branches: 
     - "**"
jobs:
  run-karma-test:

    runs-on: ubuntu-latest
    container: erawat/civicrm-extension-test:empty-1.0.2
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Verify MySQL connection from container 
      run: |
        mysql --host mysql -uroot -ppassword -e "SHOW DATABASES"

    - uses: actions/checkout@v2

    - name: Run karma test
      run: npm install 
    
    - name: Run npx gulp test
      run: npx gulp test
