name: Linters

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install php linter
      run: cd bin && ./install-php-linter && cd ..

    - name: Run phpcs linter
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
        MERGE_BRANCH:  ${{ github.head_ref }}
      run: |
        pwd
        ls -la
        git branch
        git fetch -n origin ${TARGET_BRANCH}
        git diff origin/${TARGET_BRANCH} --no-commit-id --name-only -r -- '*.php'
      #  ./bin/phpcs.phar $(git diff origin/${TARGET_BRANCH} --no-commit-id --name-only -r -- '*.php')