name: Linters

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install php linter
      run: cd bin && ./install-php-linter && cd ..

    - name: Run phpcs linter
      run: |
        echo "Pull request's target branch is: ${TARGET_BRANCH}"
        pwd
       ./bin/phpcs.phar --help
       ./bin/phpcs.phar $(git diff origin/${TARGET_BRANCH} --no-commit-id --name-only -r -- '*.php')