name: Linters

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run phpcs linter
      run: |
        cd bin && ./install-php-linter && cd ..
        pwd
        ls -la
        echo $GITHUB_REF
        echo running on branch ${GITHUB_REF##*/}
        ./bin/phpcs.phar --help
       # ./bin/phpcs.phar $(git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --no-commit-id --name-only -r -- '*.php')
