name: Linter-eslint

on:
  pull_request:
    branches: 
     - "**"
    paths:
     - "**/*.js" 

jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run npm install
      run: npm install --save-dev

    - name: Run eslint linter
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch -n origin ${TARGET_BRANCH}
        npx eslint --max-warnings=0 -c .eslintrc.json $(git diff origin/${TARGET_BRANCH} --no-commit-id --name-only -r -- '*.js') 