name: Linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run phpcs
      run: |
        cd bin && ./install-php-linter && cd ..
        git 
        pwd
        ls -la
        ./bin/phpcs.phar $(git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --no-commit-id --name-only -r -- '*.php')

    - name: run phpcs 
      run: 
