name: Linters

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    BASE_BRANCH: ${{ github.base_ref }}
  if: github.event_name == 'pull_request'

jobs:
  run-inter-phpcs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run phpcs linter
      run: |
        cd bin && ./install-php-linter && cd ..
        echo $GITHUB_REF
        echo "Pull request's base branch is: ${BASE_BRANCH}"
        echo "GITHUB_HEAD_REF : ${GITHUB_HEAD_REF}"
        echo "GITHUB_BASE_REF:  ${GITHUB_BASE_REF}""
        echo running on branch ${GITHUB_REF##*/}
        ./bin/phpcs.phar --help
       # ./bin/phpcs.phar $(git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --no-commit-id --name-only -r -- '*.php')
