name: Linter-stylelint

on:
  pull_request:
    branches: 
     - "**"
    paths:
     - "**/*.scss" 

jobs:
  run-linter-stylelint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run npm install
      run: npm install --save-dev

    - name: Run stylelint linter
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch -n origin ${TARGET_BRANCH}
        npx stylelint --config .stylelintrc $(git diff diff origin/${TARGET_BRANCH} --no-commit-id --name-only -r -- '*.scss')